language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
      - "~/.platformio"

install:
  - pip install -U platformio

script:
  - mv src/build-secrets.h src/secrets.h
  - platformio run